export const CarouselData = [
  {
    id: '1',
    title: 'Minimalist Concept',
    image: require('./src/images/Concept1.jpg'),
  },
  {
    id: '2',
    title: 'Modern Concept',
    image: require('./src/images/Concept2.jpg'),
  },
  {
    id: '3',
    title: 'Tropical Modern Concept',
    image: require('./src/images/Concept3.jpg'),
  },
];

export const features = [
  {
    id: '4',
    title: 'Material',
    logo: require('./src/icons/Feature1.png'),
    backgroundColor: ['lightblue', 'lightcyan'],
  },
  {
    id: '5',
    title: 'Consultation',
    logo: require('./src/icons/Feature2.png'),
    backgroundColor: ['lightcoral', 'lightpink'],
  },
  {
    id: '6',
    title: 'Design Details',
    logo: require('./src/icons/Feature3.png'),
    backgroundColor: ['lightgreen', 'lightseagreen'],
  },
  {
    id: '7',
    title: 'Furniture',
    logo: require('./src/icons/Feature4.png'),
    backgroundColor: ['lightsalmon', 'lightsalmon'],
  },
  {
    id: '8',
    title: 'Unit Price',
    logo: require('./src/icons/Feature5.png'),
    backgroundColor: ['lightpink', 'lightpink'],
  },
  {
    id: '9',
    title: 'House Type',
    logo: require('./src/icons/Feature6.png'),
    backgroundColor: ['lightskyblue', 'lightskyblue'],
  },
  {
    id: '10',
    title: 'Architect Contact',
    logo: require('./src/icons/Feature7.png'),
    backgroundColor: ['lightseagreen', 'lightseagreen'],
  },
  {
    id: '11',
    title: 'Transaction',
    logo: require('./src/icons/Feature8.png'),
    backgroundColor: ['lightsteelblue', 'lightsteelblue'],
  },
];

export const houseData = [
  {
    id: '1',
    title: 'Classic Italian House',
    image: require('./src/images/Toscana,Italia.png'),
    price: '15 Miliar',
    category: 'Classic',
    address: 'Toscana, Italia',
    buildingArea: 350,
    landArea: 1900,
    bathrooms: 4,
    bedrooms: 5,
  },
  {
    id: '2',
    title: 'Classic French House',
    image: require('./src/images/Provence,Prancis.jpg'),
    price: '18 Miliar',
    category: 'Classic',
    address: 'Provence, Prancis',
    buildingArea: 280,
    landArea: 800,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '3',
    title: 'Classic England House',
    image: require('./src/images/Cotswolds,Inggris.jpg'),
    price: '20 Miliar',
    category: 'Classic',
    address: 'Cotswolds, Inggris',
    buildingArea: 320,
    landArea: 900,
    bathrooms: 4,
    bedrooms: 5,
  },
  {
    id: '4',
    title: 'Classic Greece House',
    image: require('./src/images/Santorini,Yunani.jpg'),
    price: '30 Miliar',
    category: 'Classic',
    address: 'Santorini, Yunani',
    buildingArea: 400,
    landArea: 1200,
    bathrooms: 5,
    bedrooms: 6,
  },
  {
    id: '5',
    title: 'Classic Spain House',
    image: require('./src/images/Barcelona,Spanyol.jpg'),
    price: '15 Miliar',
    category: 'Classic',
    address: 'Barcelona, Spanyol',
    buildingArea: 260,
    landArea: 750,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '6',
    title: 'Classic Austria House',
    image: require('./src/images/Vienna,Austria.jpg'),
    price: '22 Miliar',
    category: 'Classic',
    address: 'Vienna, Austria',
    buildingArea: 380,
    landArea: 1100,
    bathrooms: 4,
    bedrooms: 5,
  },
  {
    id: '7',
    title: 'Classic Japan House',
    image: require('./src/images/Kyoto,Jepang.jpg'),
    price: '19 Miliar',
    category: 'Classic',
    address: 'Kyoto, Jepang',
    buildingArea: 300,
    landArea: 850,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '8',
    title: 'Classic Russia House',
    image: require('./src/images/Moscow,Rusia.jpg'),
    price: '28 Miliar',
    category: 'Classic',
    address: 'Moscow, Rusia',
    buildingArea: 450,
    landArea: 1400,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '9',
    title: 'Classic China House',
    image: require('./src/images/Beijing,Tiongkok.jpg'),
    price: '20 Miliar',
    category: 'Classic',
    address: 'Beijing, Tiongkok',
    buildingArea: 320,
    landArea: 900,
    bathrooms: 4,
    bedrooms: 5,
  },
  {
    id: '10',
    title: 'Classic India House',
    image: require('./src/images/Jaipur,India.jpg'),
    price: '16 Miliar',
    category: 'Classic',
    address: 'Jaipur, India',
    buildingArea: 280,
    landArea: 800,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '11',
    title: 'Contemporary House',
    image: require('./src/images/Concept6.jpg'),
    price: '185 Juta',
    category: 'Contemporary',
    address: '789 Oak St, Village',
    buildingArea: 220,
    landArea: 420,
    bathrooms: 3,
    bedrooms: 4,
  },
  {
    id: '21',
    title: 'Scandinavian House',
    image: require('./src/images/Concept7.jpg'),
    rating: 4.6,
    price: '320 Juta',
    category: 'Contemporary',
    address: '101 Pine St, Suburb',
    buildingArea: 240,
    landArea: 480,
    bathrooms: 2,
    bedrooms: 3,
  },
];

export const roomData = [
  {
    id: 1,
    aspectRatio: 150 / 200,
    image: require('./src/images/Search_LivingRoom_1.jpeg'),
    category: 'Living Room',
  },
  {
    id: 2,
    aspectRatio: 1,
    image: require('./src/images/Search_LivingRoom_2.jpeg'),
    category: 'Living Room',
  },
  {
    id: 3,
    aspectRatio: 120 / 100,
    image: require('./src/images/Search_LivingRoom_3.jpeg'),
    category: 'Living Room',
  },
  {
    id: 4,
    aspectRatio: 200 / 150,
    image: require('./src/images/Search_LivingRoom_4.jpeg'),
    category: 'Living Room',
  },
  {
    id: 5,
    aspectRatio: 375 / 400,
    image: require('./src/images/Search_LivingRoom_5.jpeg'),
    category: 'Living Room',
  },
  {
    aspectRatio: 500 / 400,
    id: 6,
    image: require('./src/images/Search_LivingRoom_6.jpeg'),
    category: 'Living Room',
  },
  {
    id: 7,
    aspectRatio: 1048 / 500,
    image: require('./src/images/Search_LivingRoom_7.jpeg'),
    category: 'Living Room',
  },
  {
    id: 8,
    aspectRatio: 2 / 1,
    image: require('./src/images/Search_LivingRoom_8.jpeg'),
    category: 'Living Room',
  },
  {
    id: 9,
    aspectRatio: 1,
    image: require('./src/images/Search_LivingRoom_9.jpeg'),
    category: 'Living Room',
  },
  {
    id: 10,
    aspectRatio: 375 / 400,
    image: require('./src/images/Search_LivingRoom_10.jpeg'),
    category: 'Living Room',
  },
  {
    id: 11,
    aspectRatio: 1,
    image: require('./src/images/Search_LivingRoom_11.jpeg'),
    category: 'Living Room',
  },
  {
    id: 12,
    aspectRatio: 150 / 200,
    image: require('./src/images/Search_LivingRoom_12.jpeg'),
    category: 'Living Room',
  },
  {
    id: 13,
    aspectRatio: 500 / 400,
    image: require('./src/images/Search_LivingRoom_13.jpeg'),
    category: 'Living Room',
  },
  {
    id: 14,
    aspectRatio: 200 / 150,
    image: require('./src/images/Search_LivingRoom_14.jpeg'),
    category: 'Living Room',
  },
  {
    id: 15,
    aspectRatio: 120 / 100,
    image: require('./src/images/Search_LivingRoom_15.jpeg'),
    category: 'Living Room',
  },
  {
    id: 16,
    aspectRatio: 1,
    image: require('./src/images/Search_LivingRoom_16.jpeg'),
    category: 'Living Room',
  },
  {
    id: 17,
    aspectRatio: 2 / 1,
    image: require('./src/images/Search_LivingRoom_17.jpeg'),
    category: 'Living Room',
  },
  {
    id: 18,
    aspectRatio: 150 / 200,
    image: require('./src/images/Search_LivingRoom_18.jpeg'),
    category: 'Living Room',
  },
  {
    id: 19,
    aspectRatio: 1.02,
    image: require('./src/images/Search_LivingRoom_19.jpeg'),
    category: 'Living Room',
  },
  {
    id: 20,
    aspectRatio: 1048 / 500,
    image: require('./src/images/Search_LivingRoom_20.jpeg'),
    category: 'Living Room',
  },
  {
    id: 100,
    aspectRatio: 1.35,
    image: require('./src/images/Search_BedRoom_1.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 101,
    aspectRatio: 1,
    image: require('./src/images/Search_BedRoom_2.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 102,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BedRoom_3.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 103,
    aspectRatio: 1.5,
    image: require('./src/images/Search_BedRoom_4.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 104,
    aspectRatio: 1.1,
    image: require('./src/images/Search_BedRoom_5.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 105,
    aspectRatio: 1.4,
    image: require('./src/images/Search_BedRoom_6.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 106,
    aspectRatio: 0.9,
    image: require('./src/images/Search_BedRoom_7.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 107,
    aspectRatio: 1.6,
    image: require('./src/images/Search_BedRoom_8.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 108,
    aspectRatio: 1.3,
    image: require('./src/images/Search_BedRoom_9.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 109,
    aspectRatio: 1.7,
    image: require('./src/images/Search_BedRoom_10.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 110,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BedRoom_11.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 111,
    aspectRatio: 1,
    image: require('./src/images/Search_BedRoom_12.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 112,
    aspectRatio: 1.4,
    image: require('./src/images/Search_BedRoom_13.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 113,
    aspectRatio: 1.1,
    image: require('./src/images/Search_BedRoom_14.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 114,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BedRoom_15.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 115,
    aspectRatio: 1.5,
    image: require('./src/images/Search_BedRoom_16.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 116,
    aspectRatio: 1.7,
    image: require('./src/images/Search_BedRoom_17.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 117,
    aspectRatio: 1.7,
    image: require('./src/images/Search_BedRoom_18.jpeg'),
    category: 'Bed Room',
  },
  {
    id: 118,
    aspectRatio: 1.1,
    image: require('./src/images/Search_BedRoom_19.jpeg'),
    category: 'Bed Room',
  },
  // Data Kitchen (17 data)
  {
    id: 200,
    aspectRatio: 1.5,
    image: require('./src/images/Search_Kitchen_1.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 201,
    aspectRatio: 1.3,
    image: require('./src/images/Search_Kitchen_2.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 202,
    aspectRatio: 1.1,
    image: require('./src/images/Search_Kitchen_3.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 203,
    aspectRatio: 1.2,
    image: require('./src/images/Search_Kitchen_4.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 204,
    aspectRatio: 1.4,
    image: require('./src/images/Search_Kitchen_5.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 205,
    aspectRatio: 1,
    image: require('./src/images/Search_Kitchen_6.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 206,
    aspectRatio: 1.3,
    image: require('./src/images/Search_Kitchen_7.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 207,
    aspectRatio: 1.6,
    image: require('./src/images/Search_Kitchen_8.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 208,
    aspectRatio: 1.2,
    image: require('./src/images/Search_Kitchen_9.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 209,
    aspectRatio: 1.5,
    image: require('./src/images/Search_Kitchen_10.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 210,
    aspectRatio: 1.4,
    image: require('./src/images/Search_Kitchen_11.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 211,
    aspectRatio: 1.1,
    image: require('./src/images/Search_Kitchen_12.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 212,
    aspectRatio: 1.3,
    image: require('./src/images/Search_Kitchen_13.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 213,
    aspectRatio: 1.7,
    image: require('./src/images/Search_Kitchen_14.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 214,
    aspectRatio: 1.6,
    image: require('./src/images/Search_Kitchen_15.jpeg'),
    category: 'Kitchen',
  },
  {
    id: 215,
    aspectRatio: 1.4,
    image: require('./src/images/Search_Kitchen_16.jpeg'),
    category: 'Kitchen',
  },
  // Data Bathroom (20 data)
  {
    id: 300,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BathRoom_1.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 301,
    aspectRatio: 1.1,
    image: require('./src/images/Search_BathRoom_2.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 302,
    aspectRatio: 1.3,
    image: require('./src/images/Search_BathRoom_3.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 303,
    aspectRatio: 1.5,
    image: require('./src/images/Search_BathRoom_4.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 304,
    aspectRatio: 1.4,
    image: require('./src/images/Search_BathRoom_5.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 305,
    aspectRatio: 1.6,
    image: require('./src/images/Search_BathRoom_6.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 306,
    aspectRatio: 1.3,
    image: require('./src/images/Search_BathRoom_7.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 307,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BathRoom_8.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 308,
    aspectRatio: 1.7,
    image: require('./src/images/Search_BathRoom_9.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 309,
    aspectRatio: 1.4,
    image: require('./src/images/Search_BathRoom_10.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 310,
    aspectRatio: 1.5,
    image: require('./src/images/Search_BathRoom_11.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 311,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BathRoom_12.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 312,
    aspectRatio: 1.6,
    image: require('./src/images/Search_BathRoom_13.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 313,
    aspectRatio: 1.3,
    image: require('./src/images/Search_BathRoom_14.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 314,
    aspectRatio: 1.4,
    image: require('./src/images/Search_BathRoom_15.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 315,
    aspectRatio: 1.5,
    image: require('./src/images/Search_BathRoom_16.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 316,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BathRoom_17.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 317,
    aspectRatio: 1.3,
    image: require('./src/images/Search_BathRoom_18.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 318,
    aspectRatio: 1.2,
    image: require('./src/images/Search_BathRoom_19.jpeg'),
    category: 'Bath Room',
  },
  {
    id: 319,
    aspectRatio: 1.7,
    image: require('./src/images/Search_BathRoom_20.jpeg'),
    category: 'Bath Room',
  },
];
